### ISSUE TITLE
ide crush on startup

### ISSUE THREAD

**Issue by mamahtehok** [ChrisCarini/jetbrains-auto-power-saver#3]
Hi. I install plugin, restart IDE and have crush ide with
```
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.internal.statistic.updater.StatisticsJobsScheduler'
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:215)
    at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:347)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.internal.statistic.updater.StatisticsJobsScheduler'
    at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:256)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:500)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:449)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:473)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:407)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:393)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
    ... 16 more
Caused by: java.lang.ExceptionInInitializerError
    at com.chriscarini.jetbrains.autopowersaver.productivity.AutoPowerSaverProductivityFeaturesProvider.getFeatureDescriptors(AutoPowerSaverProductivityFeaturesProvider.java:24)
    at com.intellij.featureStatistics.ProductivityFeaturesRegistryImpl.loadFeaturesFromProviders(ProductivityFeaturesRegistryImpl.java:100)
    at com.intellij.featureStatistics.ProductivityFeaturesRegistryImpl.lazyLoadFromPluginsFeaturesProviders(ProductivityFeaturesRegistryImpl.java:80)
    at com.intellij.featureStatistics.ProductivityFeaturesRegistryImpl.getFeatureDescriptor(ProductivityFeaturesRegistryImpl.java:165)
    at com.intellij.featureStatistics.FeatureUsageTrackerImpl.loadState(FeatureUsageTrackerImpl.java:110)
    at com.intellij.featureStatistics.FeatureUsageTrackerImpl.loadState(FeatureUsageTrackerImpl.java:21)
    at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:376)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:332)
    at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:119)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:95)
    at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:50)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.createAndInitialize(ServiceManagerImpl.java:227)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.lambda$getComponentInstance$0(ServiceManagerImpl.java:209)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:192)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:211)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
    at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:52)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:26)
    at com.intellij.featureStatistics.FeatureUsageTracker.getInstance(FeatureUsageTracker.java:27)
    at com.intellij.internal.statistic.utils.StatisticsUploadAssistant.isShouldShowNotification(StatisticsUploadAssistant.java:38)
    at com.intellij.internal.statistic.updater.StatisticsJobsScheduler.initComponent(StatisticsJobsScheduler.java:51)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:482)
    ... 28 more
Caused by: java.util.MissingResourceException: Can't find bundle for base name messages.autoPowerSaver, locale ru_RU
    at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
    at com.chriscarini.jetbrains.autopowersaver.messages.Messages.<clinit>(Messages.java:17)
    ... 55 more
```

**Comment by mamahtehok** [comment]
thx.
fix in this update https://plugins.jetbrains.com/plugin/11941-automatic-power-saver/update/66055

**Comment by ChrisCarini** [comment]
@all-contributors please add @mamahtehok for bug
