### ISSUE TITLE
com.intellij.diagnostic.PluginException: Cannot create extension

### ISSUE THREAD

**Issue by CrazyBoy49z** [ChrisCarini/jetbrains-auto-power-saver#87]
```
com.intellij.diagnostic.PluginException: Cannot create extension (class=com.chriscarini.jetbrains.autopowersaver.productivity.AutoPowerSaverProductivityFeaturesProvider) [Plugin: com.chriscarini.jetbrains.jetbrains-auto-power-saver]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:1057)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:70)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:31)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.notifyListeners(ExtensionPointImpl.java:747)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.lambda$registerExtensions$17(ExtensionPointImpl.java:957)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin$lambda-29(DynamicPlugins.kt:860)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:955)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:843)
	at com.intellij.ide.plugins.DynamicPlugins.access$loadPlugin(DynamicPlugins.kt:98)
	at com.intellij.ide.plugins.DynamicPlugins$loadPlugins$1.invoke(DynamicPlugins.kt:116)
	at com.intellij.ide.plugins.DynamicPlugins$loadPlugins$1.invoke(DynamicPlugins.kt:115)
	at com.intellij.ide.plugins.DynamicPlugins.updateDescriptorsWithoutRestart(DynamicPlugins.kt:180)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugins(DynamicPlugins.kt:115)
	at com.intellij.ide.plugins.DynamicPluginEnabler.enable(DynamicPluginEnabler.kt:34)
	at com.intellij.ide.plugins.newui.MyPluginModel.applyEnableDisablePlugins(MyPluginModel.java:245)
	at com.intellij.ide.plugins.newui.MyPluginModel.apply(MyPluginModel.java:185)
	at com.intellij.ide.plugins.PluginManagerConfigurable.apply(PluginManagerConfigurable.java:1779)
	at com.intellij.openapi.wm.impl.welcomeScreen.PluginsTabFactory$MyDefaultWelcomeScreenTab$2.ancestorRemoved(PluginsTabFactory.java:81)
	at java.desktop/javax.swing.AncestorNotifier.fireAncestorRemoved(AncestorNotifier.java:108)
	at java.desktop/javax.swing.AncestorNotifier.componentHidden(AncestorNotifier.java:208)
	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6483)
	at java.desktop/java.awt.Component.processEvent(Component.java:6428)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.chriscarini.jetbrains.autopowersaver.productivity.AutoPowerSaverProductivityFeaturesProvider PluginClassLoader(plugin=PluginDescriptor(name=Automatic Power Saver, id=com.chriscarini.jetbrains.jetbrains-auto-power-saver, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/PhpStorm/ch-0/223.7571.212/PhpStorm.app.plugins/'Automatic Power Saver', version=2.7.1, package=null, isBundled=false), packagePrefix=null, instanceId=176, state=active)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1525)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:947)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:24)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:49)
	... 51 more

```

```
PhpStorm 2022.3
Build #PS-223.7571.212, built on December 1, 2022
Licensed to Yurij Finiv
Subscription is active until September 17, 2023.
Runtime version: 17.0.5+1-b653.14 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3048M
Cores: 8
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=415967
    debugger.new.tool.window.layout=true
    ide.windowSystem.autoShowProcessPopup=true
    run.processes.with.pty=TRUE
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=415967

Non-Bundled Plugins:
    cc.moky.intellij.plugin.svga-support (1.0.8)
    io.aesy.regex101 (0.2)
    lermitage.intellij.extratci (1.24.0)
    com.intellij.javafx (1.0.4)
    cat.dcat.jbplug.mactabbing (1.1.0)
    com.guohanlin.JsonToAnyLanguage (1.1.0)
    com.mroche.JsonHelper (1.2.0)
    lermitage.intellij.worldclock (1.5.1)
    krasa.CpuUsageIndicator (1.14)
    bundled-phpstorm-help (223.7571.212)
    com.github.czy211.licensetemplate (2.0.0)
    MultiHighlight (3.0.0)
    lermitage.intellij.iconviewer (1.19)
    com.github.googee.laravelbuilder (0.1.3)
    ideanginx9 (0.1.9)
    com.chriscarini.jetbrains.jetbrains-auto-power-saver (2.7.1)
    com.unger1984.npmdependencychecker (0.0.3)
    ski.chrzanow.foldableprojectview (1.1.4)
    com.intellij.properties (223.7571.117)
    Key Promoter X (2022.3)
    com.mallowigi (82.0.0)
    com.wakatime.intellij.plugin (14.1.3)
    mobi.hsz.idea.gitignore (4.4.4)
    zielu.gittoolbox (213.10.5)
    LiveTemplatePreview (0.3)
    String Manipulation (9.6.1)
    com.wix.sasslint (1.1.2)
    Flagiarism (2.3)
    com.xtu.plugins.reviewer (1.0.5)
    com.funivan.idea.phpClean (2022.08.30)
    de.espend.idea.php.annotation (8.3.0)
    net.rentalhost.plugins.php.hammer (0.18.0)
    dev.nybroe.collector (0.4.0)
    ru.adelf.idea.dotenv (2022.3)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    nl.deschepers.laraveltinker (2.5.1)
    com.github.inxilpro.intellijalpine (v0.4.2)
    com.chrisrm.idea.MaterialThemeUI (8.4.0)
    io.snyk.snyk-intellij-plugin (2.4.49)
    izhangzhihao.rainbow.brackets (2022.3.5)
    fr.adrienbrault.idea.symfony2plugin (2022.1.238)
    com.laravel_idea.plugin (6.2.2.223)
    org.i18nally.jetbrainsideplugin (1.4.1.4)
    com.materkey.codepoints (1.0.2)
    lermitage.intellij.battery.status (1.25)
    com.pestphp.pest-intellij (1.8.3)

```

**Comment by ChrisCarini** [comment]
Hi @CrazyBoy49z - have you seen this issue arise recently at all in any of the newer published versions of the plugin?

**Comment by CrazyBoy49z** [comment]
> Hi @CrazyBoy49z - have you seen this issue arise recently at all in any of the newer published versions of the plugin?

I think you can close it, I haven't encountered any more problems

**Comment by ChrisCarini** [comment]
> > Hi @CrazyBoy49z - have you seen this issue arise recently at all in any of the newer published versions of the plugin?
> 
> I think you can close it, I haven't encountered any more problems

Sounds good, thank you for confirming!

**Comment by ChrisCarini** [comment]
@all-contributors please add @CrazyBoy49z for bug, maintenance
